# 项目ID
project_id="tsing"

# 服务版本号
version="v1"

###################### 公用参数 ###############################
[common]

###################### 服务参数 ###############################
[service]
# 服务ID
id="tsing-demo"

# 连接密码
secret="123456"

# 调试模式，会将详细的错误信息输出给客户端
debug=false

# 监听地址，留空表示监听0.0.0.0
# ip=""

# http监听端口，端口号为0表示不启用http
http_port=20080

# 读取超时(秒)
# read_timeout=10

# 头信息读取超时（秒）
# read_header_timeout=10

# 响应超时(秒)
# write_timeout=10

# 空闲超时(秒)
# idle_timeout=10

# 退出等待超时时间（秒）
# quit_wait_timeout=5

# 自动恢复panic
# recover=true

# 记录事件来源信息(影响性能)
# event_source=true

# 记录跟踪信息(影响性能)
# event_trace=true

# 记录404错误
event_not_found=false

# 记录405错误
event_method_not_allowed=false

# 事件中使用短路径
event_short_path=false

###################### 日志记录参数 ###############################
[logger]
# 记录级别，支持以下值，留空则禁用logger，支持: empty(不显示级别)/debug/info/warn/error
level="info"

# 日志文件的路径，如果留空则不写文件
file_path="./output.log"

# 日志时间格式(年-月-日 时:分:秒)
time_format="y-m-d h:i:s"

# 日志编码(console/json)
encode="console"

# 日志文件的权限，例如755|700|664
file_mode=664

###################### tsing center 参数 ###############################
[service_center]

# API地址，留空表示不注册服务
addr=""

# 连接密码
secret=""

# 节点生命周期(秒)
ttl=10

# 自动触活的间隔时间(秒)
touch_interval=6
# 请求超时时间(秒)
timeout=5
# 权重值
weight=1

###################### etcd 参数 ###############################
[etcd]
# 端点URL，可以写多个
endpoints=["http://127.0.0.1:2379"]

# username=""

# password=""

# dial_timeout=5

# auto_sync_interval=0

# dial_keep_aliveTime=0

# dial_keep_aliveTimeout=0

# max_call_send_msg_size=0

# max_call_recv_msg_size=0

# reject_old_cluster=false

# permit_without_stream=false

###################### redis 参数 ###############################
[redis]
# redis地址:端口
addr="127.0.0.1:6379"

# redis连接密码
# password=""

# redis的库索引
# db=0

# 键名前缀
key_prefix=""


###################### 数据库参数 ###############################
[database]
# 地址
addr="127.0.0.1:5432"

# 账号
user="postgres"

# 密码
password="123456"

# 库名
name="tsing"

# 记录SQL语句，建议仅开发时使用
stmt_log=false

# 连接超时(秒)
# dial_timeout=5

# 读超时(秒)
# read_timeout=10

# 写超时(秒)
# write_timeout=10

# 连接池大小
# pool_size=200

###################### session 参数 ###############################
[session]
# session id的加密密钥
# 由于session id在客户端可见，因此需要加密
# 密钥的长度16,24,32对应AES-128,AES-192,AES-256算
aes_key="1111111111111111"

# session id的cookie键名
cookie_name="sessionid"

# HTTP Only
# http_only=false

# 启用HTTPS
# secure=false

# 最大生命周期(分)
# max_age=60

# 空闲超时(分)
# idle_time=40

# redis的键名前缀
redis_key_prefix="sess_"

# redis的连接地址
redis_addr="127.0.0.1:6379"

# redis的连接密码
redis_password="123456"

# redis的库编号
# redis_db=0
