# 调试模式，会将调试和详细的错误信息打印或输出给客户端，并启用pprof
debug=true

###################### 服务参数 ###############################
[service]
# 连接密码
secret=""

# 监听地址，留空表示监听0.0.0.0
# ip=""

# http监听端口，端口号为0表示不启用http
http_port=20080

# 读取超时(秒)
# read_timeout=10

# 头信息读取超时（秒）
# read_header_timeout=10

# 响应超时(秒)，开启debug时，此值会自动>60
# write_timeout=10

# 空闲超时(秒)
# idle_timeout=10

# 退出等待超时时间（秒）
# quit_wait_timeout=5

# 记录404错误
# event_not_found=false

# 记录405错误
# event_method_not_allowed=false

# 事件中使用短路径
# event_short_path=false

###################### 日志记录参数 ###############################
[logger]
# 记录级别: debug(默认)/info/warn/error
level="debug"

# 日志文件的路径，如果留空则不写文件
file_path=""

# 日志时间格式，默认：y年-m月-d日 h时:i分:s秒
# time_format="y-m-d h:i:s"

# 日志编码：console默认/json
# encode="console"

# 日志文件的权限，默认：0600
# file_mode=0600

###################### tsing center 参数 ###############################
[service_center]
# API地址，留空表示不注册服务
addr=""

# 连接密码
# secret=""

# 节点生命周期(秒)
# ttl=10

# 自动触活的间隔时间(秒)
# touch_interval=6

# 请求超时时间(秒)
# timeout=5

# 权重值
# weight=1

###################### etcd 参数 ###############################
[etcd]
# 端点URL，[]string类型，可以写多个
endpoints=["http://127.0.0.1:2379"]
# username=""
# password=""
# dial_timeout=5
# auto_sync_interval=0
# dial_keep_aliveTime=0
# dial_keep_aliveTimeout=0
# max_call_send_msg_size=0
# max_call_recv_msg_size=0
# reject_old_cluster=false
# permit_without_stream=false

###################### redis 参数 ###############################
[redis]
# redis地址:端口
addr="127.0.0.1:6379"

# redis连接账号
# username=""

# redis连接密码
# password=""

# redis的库索引
# db=0

# 键名前缀
#key_prefix=""


###################### 数据库参数 ###############################
[database]
# 地址
addr="127.0.0.1:5432"

# 账号
user="postgres"

# 密码
password="123456"

# 库名
name="tsing"

# 连接超时(秒)
# dial_timeout=5

# 读超时(秒)
# read_timeout=10

# 写超时(秒)
# write_timeout=10

# 连接池大小
# pool_size=200

###################### session 参数 ###############################
[session]
# session id的cookie键名
cookie_key="sessionid"

# HTTP Only
# http_only=false

# 启用HTTPS
# secure=false

# 空闲超时(分)
# idle_timeout=40

# redis的键名前缀
redis_key_prefix="sess_"

# redis的连接地址
redis_addr="127.0.0.1:6379"

# redis的连接账号
# redis_username="dxvgef"

# redis的连接密码
redis_password="123456"

# redis的库
# redis_db=0
